# Generated by Django 2.1 on 2018-08-26 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shape', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('form_submitted', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, choices=[(None, 'Choose symbol'), ('1', 'Default'), ('3', 'Symbol_1'), ('2', 'Symbol_2')], max_length=10, null=True)),
                ('forms', models.ManyToManyField(blank=True, null=True, related_name='project_req_2', to='school.Form')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_req_1', to='school.Profile')),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='project_req_3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
