# Generated by Django 2.1 on 2018-08-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20180827_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='forms',
        ),
        migrations.AddField(
            model_name='project',
            name='forms',
            field=models.ManyToManyField(blank=True, related_name='project_req_2', to='school.Form'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ManyToManyField(blank=True, related_name='project_req_1', to='school.Profile'),
        ),
    ]
