# Generated by Django 2.1 on 2018-08-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20180827_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
