# Generated by Django 2.1 on 2018-08-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20180831_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
